# Site settings
title: Sha Naa Naa
email: marteki@gmail.com 
tagline: "Naa Marteki Reed, user experience designer"
description: > # this means to ignore newlines until "baseurl:"
  The website for Naa Marteki Reed, user experience designer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.marteki.com" # the base hostname & protocol for your site
version: 1.0
twitter_username: marteki
github_username:  marteki
permalinks: pretty
paginate: 5
paginate_path: "page:num"

# About/contact
author:
  name:              Naa Marteki Reed 
  url:               https://twitter.com/marteki
  email:             marteki@gmail.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
